// The dashboard catalog: product areas, their metrics and dimensions, and the dashboard
// archetypes (hand-composed widget layouts) that scripts/vizdash-gen.mjs instantiates
// once per scope (e.g. "Pipeline · EMEA · Enterprise").
//
// Widget kinds (see scripts/vizdash-gen.mjs, emitWidget):
//   trend      metrics over time (line or area, chosen per dashboard)
//   cumulative running total of one metric with a target line
//   bars       one metric over time as bars
//   stack      one metric over time split by a dimension (stackedArea | stackedBar | percentArea)
//   combo      bars of one metric and a line of another (two axes)
//   ranked     one metric by a dimension, ranked bars
//   donut      one metric by a dimension, share of total
//   heatmap    one metric over two dimensions (weekday/hour/month are built in)
//   treemap    one metric over two nested dimensions
//   sankey     one metric flowing through 2-3 dimensions
//   funnel     conversion through named steps from `top` entrants
//   cohort     retention triangle
//   histogram  per-item distribution of one metric
//   box        per-item distribution of one metric by a dimension
//   scatter    entities placed by two metrics, colored by a dimension
//   gauge      one metric against a target (target = factor x the previous period's value)
//   calendar   one metric per day over the last year
//   radar      several metrics compared across a dimension's values

const dims = (o) =>
  Object.fromEntries(Object.entries(o).map(([key, [label, values]]) => [key, { label, values }]));

const REGIONS = ["North America", "EMEA", "APAC", "LATAM", "ANZ", "Japan"];

export const AREAS = [
  {
    key: "sales",
    label: "Sales",
    icon: "briefcase",
    accent: "#3b6fe0",
    description: "Pipeline, bookings and forecast for every territory and segment.",
    team: "Revenue Operations",
    headline: ["bookings", "pipeline", "win_rate"],
    scopeAxes: ["region", "segment", "product"],
    filters: { segment: "segment", region: "region" },
    dimensions: dims({
      region: ["Region", REGIONS],
      segment: ["Segment", ["SMB", "Mid-Market", "Enterprise", "Strategic"]],
      product: ["Product", ["Core", "Analytics", "Security", "Platform", "Add-ons"]],
      stage: ["Stage", ["Prospecting", "Discovery", "Proposal", "Negotiation", "Commit"]],
      source: ["Source", ["Inbound", "Outbound", "Partner", "Events", "Expansion"]],
      outcome: ["Outcome", ["Won", "Lost", "Slipped"]],
      rep: [
        "Rep",
        [
          "A. Okafor",
          "J. Tanaka",
          "M. Rossi",
          "P. Patel",
          "S. Larsen",
          "D. Alvarez",
          "H. Park",
          "L. Moreau",
          "N. Mensah",
          "R. Silva",
        ],
      ],
      loss_reason: [
        "Loss reason",
        ["Price", "Timing", "Competitor", "No decision", "Missing feature", "Champion left"],
      ],
    }),
    metrics: [
      { key: "bookings", label: "Bookings", unit: "currency", base: 182000, trend: 0.18 },
      { key: "pipeline", label: "Open pipeline", unit: "currency", base: 690000, trend: 0.14 },
      {
        key: "quota",
        label: "Quota",
        unit: "currency",
        base: 200000,
        trend: 0.15,
        noise: 0.01,
        season: 0,
      },
      { key: "win_rate", label: "Win rate", unit: "percent", base: 0.27, trend: 0.03, noise: 0.05 },
      {
        key: "deal_size",
        label: "Avg deal size",
        unit: "currency",
        base: 38500,
        trend: 0.08,
        agg: "avg",
      },
      {
        key: "cycle_days",
        label: "Sales cycle",
        unit: "days",
        base: 64,
        trend: -0.05,
        good: "down",
      },
      { key: "opportunities", label: "New opportunities", unit: "count", base: 46 },
      { key: "meetings", label: "Meetings held", unit: "count", base: 210 },
      { key: "expansion", label: "Expansion ARR", unit: "currency", base: 41000, trend: 0.22 },
      {
        key: "churned_arr",
        label: "Churned ARR",
        unit: "currency",
        base: 12500,
        trend: -0.04,
        good: "down",
      },
      {
        key: "discount",
        label: "Avg discount",
        unit: "percent",
        base: 0.14,
        good: "down",
        noise: 0.04,
      },
      { key: "forecast", label: "Forecast (commit)", unit: "currency", base: 196000, noise: 0.03 },
    ],
    entities: {
      deal: {
        label: "Deal",
        plural: "Deals",
        pool: "company",
        statuses: ["Discovery", "Proposal", "Negotiation", "Commit", "Won", "Lost"],
      },
      rep: {
        label: "Rep",
        plural: "Reps",
        pool: "person",
        statuses: ["On track", "At risk", "Ramping"],
      },
      account: {
        label: "Account",
        plural: "Accounts",
        pool: "company",
        statuses: ["Active", "At risk", "Churned", "Expanding"],
      },
    },
    archetypes: [
      {
        key: "pipeline",
        label: "Pipeline",
        description:
          "Open pipeline by stage and source, coverage against quota, and the deals that move it.",
        kpis: ["pipeline", "opportunities", "win_rate", "deal_size"],
        widgets: [
          {
            kind: "stack",
            metric: "pipeline",
            by: "stage",
            variant: "stackedArea",
            title: "Pipeline by stage",
          },
          { kind: "ranked", metric: "pipeline", by: "source", title: "Pipeline by source" },
          {
            kind: "sankey",
            metric: "pipeline",
            stages: ["source", "stage", "outcome"],
            title: "Where pipeline goes",
          },
          {
            kind: "trend",
            metrics: ["opportunities", "meetings"],
            title: "Opportunities and meetings",
          },
        ],
        optional: [
          { kind: "histogram", metric: "deal_size", title: "Deal size distribution" },
          { kind: "donut", metric: "pipeline", by: "product", title: "Pipeline mix by product" },
          {
            kind: "heatmap",
            metric: "opportunities",
            rows: "weekday",
            cols: "hour",
            title: "When opportunities are created",
          },
        ],
        table: {
          entity: "deal",
          title: "Open deals",
          metrics: ["deal_size", "cycle_days", "win_rate"],
        },
      },
      {
        key: "bookings",
        label: "Bookings",
        description: "Closed-won bookings against quota, by product and rep.",
        kpis: ["bookings", "quota", "deal_size", "discount"],
        widgets: [
          {
            kind: "cumulative",
            metric: "bookings",
            target: "quota",
            title: "Bookings vs quota (cumulative)",
          },
          {
            kind: "stack",
            metric: "bookings",
            by: "product",
            variant: "stackedBar",
            title: "Bookings by product",
          },
          { kind: "ranked", metric: "bookings", by: "rep", title: "Top reps" },
          { kind: "gauge", metric: "bookings", target: 1.08, title: "Quota attainment" },
        ],
        optional: [
          { kind: "donut", metric: "bookings", by: "segment", title: "Bookings by segment" },
          { kind: "calendar", metric: "bookings", title: "Daily bookings, last 12 months" },
          { kind: "box", metric: "deal_size", by: "product", title: "Deal size by product" },
        ],
        table: { entity: "deal", title: "Recently closed", metrics: ["deal_size", "discount"] },
      },
      {
        key: "forecast",
        label: "Forecast",
        description: "Commit and best-case forecast against bookings and quota for the quarter.",
        kpis: ["forecast", "bookings", "pipeline", "win_rate"],
        widgets: [
          { kind: "trend", metrics: ["forecast", "bookings"], title: "Forecast vs bookings" },
          { kind: "combo", bar: "pipeline", line: "win_rate", title: "Pipeline and win rate" },
          { kind: "ranked", metric: "forecast", by: "rep", title: "Forecast by rep" },
          { kind: "gauge", metric: "forecast", target: 1.04, title: "Forecast coverage" },
        ],
        optional: [
          {
            kind: "stack",
            metric: "forecast",
            by: "stage",
            variant: "percentArea",
            title: "Forecast mix by stage",
          },
          {
            kind: "scatter",
            x: "deal_size",
            y: "win_rate",
            by: "segment",
            title: "Deal size vs win rate",
          },
        ],
        table: { entity: "deal", title: "Commit deals", metrics: ["deal_size", "win_rate"] },
      },
      {
        key: "rep-performance",
        label: "Rep performance",
        description: "Attainment, activity and win rate per rep.",
        kpis: ["bookings", "meetings", "win_rate", "cycle_days"],
        widgets: [
          { kind: "ranked", metric: "bookings", by: "rep", title: "Bookings by rep" },
          {
            kind: "radar",
            metrics: ["win_rate", "deal_size", "meetings", "opportunities", "expansion"],
            by: "segment",
            title: "Rep profile by segment",
          },
          {
            kind: "scatter",
            x: "meetings",
            y: "bookings",
            by: "segment",
            size: "deal_size",
            pool: "person",
            title: "Activity vs bookings",
          },
          {
            kind: "heatmap",
            metric: "meetings",
            rows: "rep",
            cols: "weekday",
            title: "Meetings by rep and weekday",
          },
        ],
        optional: [
          { kind: "box", metric: "cycle_days", by: "segment", title: "Sales cycle by segment" },
          { kind: "trend", metrics: ["meetings"], title: "Meetings over time" },
        ],
        table: { entity: "rep", title: "Reps", metrics: ["bookings", "win_rate", "meetings"] },
      },
      {
        key: "win-loss",
        label: "Win / loss",
        description: "Why deals are won and lost, by stage, competitor and reason.",
        kpis: ["win_rate", "deal_size", "cycle_days", "discount"],
        widgets: [
          { kind: "trend", metrics: ["win_rate"], title: "Win rate" },
          { kind: "donut", metric: "opportunities", by: "loss_reason", title: "Loss reasons" },
          {
            kind: "sankey",
            metric: "opportunities",
            stages: ["source", "stage", "outcome"],
            title: "Opportunity outcomes",
          },
          { kind: "box", metric: "cycle_days", by: "outcome", title: "Cycle length by outcome" },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "win_rate",
            rows: "segment",
            cols: "product",
            title: "Win rate by segment and product",
          },
          { kind: "histogram", metric: "discount", title: "Discount distribution" },
        ],
        table: { entity: "deal", title: "Lost deals", metrics: ["deal_size", "discount"] },
      },
      {
        key: "territory",
        label: "Territory",
        description: "Coverage, penetration and growth across the territory's accounts.",
        kpis: ["bookings", "pipeline", "expansion", "churned_arr"],
        widgets: [
          {
            kind: "treemap",
            metric: "bookings",
            outer: "segment",
            inner: "product",
            title: "Bookings by segment and product",
          },
          {
            kind: "trend",
            metrics: ["bookings", "expansion"],
            title: "New and expansion bookings",
          },
          { kind: "ranked", metric: "pipeline", by: "product", title: "Pipeline by product" },
          {
            kind: "heatmap",
            metric: "bookings",
            rows: "segment",
            cols: "month",
            title: "Seasonality by segment",
          },
        ],
        optional: [
          { kind: "donut", metric: "bookings", by: "source", title: "Bookings by source" },
        ],
        table: {
          entity: "account",
          title: "Top accounts",
          metrics: ["bookings", "expansion", "churned_arr"],
        },
      },
      {
        key: "expansion",
        label: "Expansion",
        description: "Net revenue retention: expansion against churn in the installed base.",
        kpis: ["expansion", "churned_arr", "deal_size", "win_rate"],
        widgets: [
          {
            kind: "combo",
            bar: "expansion",
            line: "win_rate",
            title: "Expansion ARR and win rate",
          },
          { kind: "trend", metrics: ["expansion", "churned_arr"], title: "Expansion vs churn" },
          { kind: "cohort", periods: 10, grain: "month", title: "Account retention by cohort" },
          { kind: "ranked", metric: "expansion", by: "product", title: "Expansion by product" },
        ],
        optional: [
          {
            kind: "scatter",
            x: "deal_size",
            y: "expansion",
            by: "segment",
            title: "Account size vs expansion",
          },
        ],
        table: { entity: "account", title: "Accounts", metrics: ["expansion", "churned_arr"] },
      },
    ],
  },
  {
    key: "marketing",
    label: "Marketing",
    icon: "megaphone",
    accent: "#c2417a",
    description: "Spend, reach and conversion of every channel and campaign.",
    team: "Growth Marketing",
    headline: ["spend", "leads", "roas"],
    scopeAxes: ["channel", "region", "persona"],
    filters: { segment: "device", region: "region" },
    dimensions: dims({
      channel: [
        "Channel",
        [
          "Paid Search",
          "Paid Social",
          "Organic",
          "Email",
          "Referral",
          "Display",
          "Events",
          "Affiliates",
        ],
      ],
      region: ["Region", REGIONS],
      persona: ["Persona", ["Developers", "Data teams", "IT admins", "Executives"]],
      device: ["Device", ["Desktop", "Mobile", "Tablet"]],
      campaign_type: [
        "Campaign type",
        ["Acquisition", "Retargeting", "Brand", "Nurture", "Launch"],
      ],
      content: [
        "Content",
        ["Blog", "Docs", "Case study", "Webinar", "Comparison", "Pricing", "Changelog"],
      ],
      touch: ["Touch", ["First touch", "Middle touch", "Last touch"]],
      stage: ["Stage", ["Visitor", "Lead", "MQL", "SQL", "Opportunity"]],
      country: [
        "Country",
        [
          "US",
          "UK",
          "Germany",
          "France",
          "Japan",
          "Brazil",
          "India",
          "Canada",
          "Australia",
          "Spain",
        ],
      ],
    }),
    metrics: [
      { key: "spend", label: "Spend", unit: "currency", base: 42000, good: "down", trend: 0.1 },
      { key: "impressions", label: "Impressions", unit: "count", base: 2_400_000 },
      { key: "clicks", label: "Clicks", unit: "count", base: 41000 },
      { key: "ctr", label: "CTR", unit: "percent", base: 0.017, noise: 0.06 },
      { key: "cpc", label: "CPC", unit: "currency", base: 1.84, good: "down", agg: "avg" },
      { key: "leads", label: "Leads", unit: "count", base: 1350, trend: 0.16 },
      { key: "mqls", label: "MQLs", unit: "count", base: 420, trend: 0.14 },
      { key: "sqls", label: "SQLs", unit: "count", base: 118 },
      { key: "cac", label: "CAC", unit: "currency", base: 1480, good: "down", agg: "avg" },
      { key: "roas", label: "ROAS", unit: "ratio", base: 3.4, noise: 0.05 },
      { key: "sessions", label: "Sessions", unit: "count", base: 96000, trend: 0.2 },
      { key: "conversion", label: "Conversion rate", unit: "percent", base: 0.031 },
      { key: "open_rate", label: "Email open rate", unit: "percent", base: 0.29 },
      { key: "bounce", label: "Bounce rate", unit: "percent", base: 0.46, good: "down" },
    ],
    entities: {
      campaign: {
        label: "Campaign",
        plural: "Campaigns",
        pool: "campaign",
        statuses: ["Live", "Paused", "Scheduled", "Ended"],
      },
      page: {
        label: "Page",
        plural: "Pages",
        pool: "feature",
        statuses: ["Live", "Draft", "Testing"],
      },
    },
    archetypes: [
      {
        key: "campaigns",
        label: "Campaign performance",
        description: "Spend, leads and return of the running campaigns.",
        kpis: ["spend", "leads", "cac", "roas"],
        widgets: [
          { kind: "combo", bar: "spend", line: "roas", title: "Spend and ROAS" },
          {
            kind: "stack",
            metric: "leads",
            by: "campaign_type",
            variant: "stackedBar",
            title: "Leads by campaign type",
          },
          {
            kind: "scatter",
            x: "spend",
            y: "leads",
            by: "campaign_type",
            pool: "campaign",
            title: "Spend vs leads per campaign",
          },
          { kind: "ranked", metric: "leads", by: "content", title: "Leads by content" },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "clicks",
            rows: "weekday",
            cols: "hour",
            title: "Clicks by hour",
          },
          { kind: "histogram", metric: "cpc", title: "CPC distribution" },
        ],
        table: {
          entity: "campaign",
          title: "Campaigns",
          metrics: ["spend", "leads", "roas", "ctr"],
        },
      },
      {
        key: "channel-mix",
        label: "Channel mix",
        description: "Where spend goes and what each channel returns.",
        kpis: ["spend", "sessions", "conversion", "cac"],
        widgets: [
          {
            kind: "stack",
            metric: "spend",
            by: "channel",
            variant: "percentArea",
            title: "Spend mix by channel",
          },
          { kind: "donut", metric: "leads", by: "channel", title: "Leads by channel" },
          {
            kind: "radar",
            metrics: ["ctr", "conversion", "roas", "open_rate"],
            by: "campaign_type",
            title: "Channel efficiency",
          },
          {
            kind: "treemap",
            metric: "spend",
            outer: "channel",
            inner: "device",
            title: "Spend by channel and device",
          },
        ],
        optional: [
          { kind: "ranked", metric: "sessions", by: "country", title: "Sessions by country" },
          { kind: "box", metric: "cac", by: "campaign_type", title: "CAC by campaign type" },
        ],
        table: { entity: "campaign", title: "Campaigns by spend", metrics: ["spend", "cac"] },
      },
      {
        key: "funnel",
        label: "Funnel",
        description: "Conversion from visit to opportunity, and where it leaks.",
        kpis: ["sessions", "leads", "mqls", "sqls"],
        widgets: [
          {
            kind: "funnel",
            steps: ["Visit", "Signup", "Lead", "MQL", "SQL", "Opportunity"],
            top: 96000,
            title: "Visit to opportunity",
          },
          { kind: "trend", metrics: ["leads", "mqls", "sqls"], title: "Leads, MQLs, SQLs" },
          {
            kind: "sankey",
            metric: "leads",
            stages: ["channel", "stage"],
            title: "Leads by channel and stage",
          },
          { kind: "trend", metrics: ["conversion"], title: "Visit-to-lead conversion" },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "conversion",
            rows: "device",
            cols: "content",
            title: "Conversion by device and content",
          },
        ],
        table: {
          entity: "page",
          title: "Top landing pages",
          metrics: ["sessions", "conversion", "bounce"],
        },
      },
      {
        key: "attribution",
        label: "Attribution",
        description: "Pipeline credited to each channel by touch position.",
        kpis: ["leads", "sqls", "cac", "roas"],
        widgets: [
          {
            kind: "sankey",
            metric: "sqls",
            stages: ["channel", "touch", "stage"],
            title: "Touch paths to SQL",
          },
          {
            kind: "heatmap",
            metric: "sqls",
            rows: "channel",
            cols: "touch",
            title: "SQL credit by channel and touch",
          },
          { kind: "ranked", metric: "sqls", by: "channel", title: "SQLs by channel" },
          { kind: "trend", metrics: ["roas"], title: "Blended ROAS" },
        ],
        optional: [{ kind: "donut", metric: "spend", by: "channel", title: "Spend share" }],
        table: { entity: "campaign", title: "Campaign credit", metrics: ["sqls", "spend"] },
      },
      {
        key: "web",
        label: "Web traffic",
        description: "Sessions, engagement and conversion on the marketing site.",
        kpis: ["sessions", "bounce", "conversion", "clicks"],
        widgets: [
          { kind: "trend", metrics: ["sessions"], title: "Sessions" },
          {
            kind: "stack",
            metric: "sessions",
            by: "device",
            variant: "stackedArea",
            title: "Sessions by device",
          },
          {
            kind: "heatmap",
            metric: "sessions",
            rows: "weekday",
            cols: "hour",
            title: "Traffic by hour",
          },
          { kind: "ranked", metric: "sessions", by: "country", title: "Top countries" },
          { kind: "calendar", metric: "sessions", title: "Daily sessions" },
        ],
        optional: [{ kind: "histogram", metric: "bounce", title: "Bounce rate by page" }],
        table: { entity: "page", title: "Pages", metrics: ["sessions", "bounce", "conversion"] },
      },
      {
        key: "email",
        label: "Email",
        description: "Sends, opens and clicks of lifecycle and campaign email.",
        kpis: ["open_rate", "ctr", "leads", "bounce"],
        widgets: [
          { kind: "trend", metrics: ["open_rate", "ctr"], title: "Open and click rate" },
          {
            kind: "heatmap",
            metric: "open_rate",
            rows: "weekday",
            cols: "hour",
            scheme: "purples",
            title: "Opens by send time",
          },
          { kind: "bars", metric: "leads", title: "Leads from email" },
          { kind: "ranked", metric: "clicks", by: "campaign_type", title: "Clicks by program" },
        ],
        optional: [
          {
            kind: "cohort",
            periods: 8,
            grain: "week",
            title: "Subscriber engagement by signup week",
          },
        ],
        table: { entity: "campaign", title: "Sends", metrics: ["open_rate", "ctr", "leads"] },
      },
      {
        key: "seo",
        label: "SEO",
        description: "Organic search: impressions, clicks and the content that ranks.",
        kpis: ["impressions", "clicks", "ctr", "sessions"],
        widgets: [
          { kind: "combo", bar: "impressions", line: "ctr", title: "Impressions and CTR" },
          { kind: "ranked", metric: "clicks", by: "content", title: "Clicks by content type" },
          {
            kind: "treemap",
            metric: "sessions",
            outer: "content",
            inner: "country",
            title: "Organic sessions by content and country",
          },
          { kind: "trend", metrics: ["sessions"], title: "Organic sessions" },
        ],
        optional: [
          {
            kind: "scatter",
            x: "impressions",
            y: "ctr",
            by: "content",
            pool: "feature",
            title: "Reach vs CTR per page",
          },
        ],
        table: { entity: "page", title: "Ranking pages", metrics: ["clicks", "ctr", "sessions"] },
      },
    ],
  },
  {
    key: "finance",
    label: "Finance",
    icon: "wallet",
    accent: "#2fa37a",
    description: "P&L, cash, budgets and receivables per entity and department.",
    team: "FP&A",
    headline: ["revenue", "gross_margin", "cash"],
    scopeAxes: ["entity", "department", "currency"],
    filters: { segment: "cost_center", region: "region" },
    dimensions: dims({
      entity: [
        "Entity",
        ["Holdings Inc.", "Europe GmbH", "UK Ltd.", "Japan KK", "Brasil Ltda.", "Australia Pty"],
      ],
      department: [
        "Department",
        [
          "Engineering",
          "Sales",
          "Marketing",
          "G&A",
          "Customer Success",
          "Product",
          "Operations",
          "Finance",
        ],
      ],
      currency: ["Currency", ["USD", "EUR", "GBP", "JPY"]],
      region: ["Region", REGIONS],
      cost_center: ["Cost center", ["CC-100", "CC-200", "CC-310", "CC-420", "CC-500"]],
      account: [
        "GL account",
        [
          "Salaries",
          "Cloud hosting",
          "Software",
          "Travel",
          "Facilities",
          "Contractors",
          "Advertising",
          "Legal",
        ],
      ],
      aging: ["Aging bucket", ["Current", "1-30", "31-60", "61-90", "90+"]],
      revenue_type: ["Revenue type", ["Subscription", "Usage", "Services", "Hardware"]],
      flow: ["Cash flow", ["Operating", "Investing", "Financing"]],
      vendor: [
        "Vendor",
        [
          "Acme Cloud",
          "Globex Hosting",
          "Kinetic Staffing",
          "Lattice Security",
          "Nexus Telecom",
          "Monarch Facilities",
        ],
      ],
    }),
    metrics: [
      { key: "revenue", label: "Revenue", unit: "currency", base: 410000, trend: 0.21 },
      { key: "cogs", label: "COGS", unit: "currency", base: 98000, good: "down" },
      { key: "gross_margin", label: "Gross margin", unit: "percent", base: 0.76, noise: 0.015 },
      { key: "opex", label: "Operating expenses", unit: "currency", base: 265000, good: "down" },
      { key: "ebitda", label: "EBITDA", unit: "currency", base: 61000, noise: 0.2 },
      {
        key: "cash",
        label: "Cash balance",
        unit: "currency",
        base: 1_900_000,
        agg: "avg",
        noise: 0.01,
        season: 0.02,
      },
      { key: "burn", label: "Net burn", unit: "currency", base: 21000, good: "down", noise: 0.3 },
      {
        key: "ar",
        label: "Receivables",
        unit: "currency",
        base: 3_200_000,
        agg: "avg",
        good: "down",
        noise: 0.02,
      },
      { key: "dso", label: "DSO", unit: "days", base: 47, good: "down" },
      { key: "budget", label: "Budget", unit: "currency", base: 272000, noise: 0.005, season: 0 },
      {
        key: "variance",
        label: "Budget variance",
        unit: "percent",
        base: 0.035,
        good: "down",
        noise: 0.3,
      },
      { key: "invoices", label: "Invoices issued", unit: "count", base: 640 },
      { key: "collections", label: "Collections", unit: "currency", base: 395000 },
      {
        key: "deferred",
        label: "Deferred revenue",
        unit: "currency",
        base: 5_100_000,
        agg: "avg",
        noise: 0.01,
      },
    ],
    entities: {
      invoice: {
        label: "Invoice",
        plural: "Invoices",
        pool: "invoice",
        statuses: ["Paid", "Open", "Overdue", "Disputed"],
      },
      vendor: {
        label: "Vendor",
        plural: "Vendors",
        pool: "vendor",
        statuses: ["Approved", "Pending", "Under review"],
      },
      line: {
        label: "Budget line",
        plural: "Budget lines",
        pool: "role",
        statuses: ["On track", "At risk", "Over"],
      },
    },
    archetypes: [
      {
        key: "pnl",
        label: "P&L",
        description: "Revenue, cost of revenue and operating expense down to EBITDA.",
        kpis: ["revenue", "gross_margin", "opex", "ebitda"],
        widgets: [
          { kind: "trend", metrics: ["revenue", "opex"], title: "Revenue vs operating expense" },
          {
            kind: "combo",
            bar: "revenue",
            line: "gross_margin",
            title: "Revenue and gross margin",
          },
          {
            kind: "stack",
            metric: "revenue",
            by: "revenue_type",
            variant: "stackedBar",
            title: "Revenue by type",
          },
          { kind: "ranked", metric: "opex", by: "department", title: "Opex by department" },
        ],
        optional: [
          {
            kind: "treemap",
            metric: "opex",
            outer: "department",
            inner: "account",
            title: "Opex by department and account",
          },
          {
            kind: "heatmap",
            metric: "revenue",
            rows: "revenue_type",
            cols: "month",
            title: "Revenue seasonality",
          },
        ],
        table: { entity: "line", title: "P&L lines", metrics: ["opex", "budget", "variance"] },
      },
      {
        key: "cash",
        label: "Cash flow",
        description: "Cash position, burn, and operating, investing and financing flows.",
        kpis: ["cash", "burn", "collections", "dso"],
        widgets: [
          { kind: "trend", metrics: ["cash"], title: "Cash balance" },
          {
            kind: "sankey",
            metric: "collections",
            stages: ["revenue_type", "flow", "department"],
            title: "Where cash goes",
          },
          { kind: "bars", metric: "burn", title: "Net burn" },
          { kind: "trend", metrics: ["collections", "revenue"], title: "Collections vs revenue" },
        ],
        optional: [{ kind: "calendar", metric: "collections", title: "Daily collections" }],
        table: {
          entity: "invoice",
          title: "Largest open invoices",
          metrics: ["collections", "dso"],
        },
      },
      {
        key: "budget",
        label: "Budget vs actual",
        description: "Spend against plan by department and account, with variance.",
        kpis: ["opex", "budget", "variance", "ebitda"],
        widgets: [
          {
            kind: "cumulative",
            metric: "opex",
            target: "budget",
            title: "Cumulative spend vs budget",
          },
          {
            kind: "heatmap",
            metric: "variance",
            rows: "department",
            cols: "month",
            scheme: "oranges",
            title: "Variance by department and month",
          },
          { kind: "ranked", metric: "opex", by: "account", title: "Spend by account" },
          { kind: "gauge", metric: "opex", target: 1.02, title: "Budget used" },
        ],
        optional: [
          { kind: "box", metric: "opex", by: "department", title: "Spend per line by department" },
        ],
        table: { entity: "line", title: "Budget lines", metrics: ["budget", "opex", "variance"] },
      },
      {
        key: "receivables",
        label: "AR aging",
        description: "Receivables by aging bucket, DSO and collection performance.",
        kpis: ["ar", "dso", "collections", "invoices"],
        widgets: [
          {
            kind: "stack",
            metric: "ar",
            by: "aging",
            variant: "stackedArea",
            title: "Receivables by aging bucket",
          },
          { kind: "donut", metric: "ar", by: "aging", title: "Aging mix" },
          { kind: "trend", metrics: ["dso"], title: "DSO" },
          { kind: "histogram", metric: "dso", title: "Days to pay, per invoice" },
        ],
        optional: [{ kind: "ranked", metric: "ar", by: "entity", title: "Receivables by entity" }],
        table: { entity: "invoice", title: "Overdue invoices", metrics: ["ar", "dso"] },
      },
      {
        key: "opex",
        label: "Opex breakdown",
        description: "Operating expense by account, vendor and cost center.",
        kpis: ["opex", "cogs", "burn", "variance"],
        widgets: [
          {
            kind: "treemap",
            metric: "opex",
            outer: "account",
            inner: "cost_center",
            title: "Opex by account and cost center",
          },
          {
            kind: "stack",
            metric: "opex",
            by: "account",
            variant: "percentArea",
            title: "Opex mix over time",
          },
          { kind: "ranked", metric: "opex", by: "vendor", title: "Top vendors" },
          { kind: "trend", metrics: ["opex", "cogs"], title: "Opex and COGS" },
        ],
        optional: [
          {
            kind: "scatter",
            x: "opex",
            y: "variance",
            by: "department",
            pool: "vendor",
            title: "Spend vs variance per vendor",
          },
        ],
        table: { entity: "vendor", title: "Vendors", metrics: ["opex", "variance"] },
      },
      {
        key: "revenue",
        label: "Revenue recognition",
        description: "Recognized and deferred revenue by type.",
        kpis: ["revenue", "deferred", "invoices", "gross_margin"],
        widgets: [
          {
            kind: "stack",
            metric: "revenue",
            by: "revenue_type",
            variant: "stackedArea",
            title: "Recognized revenue by type",
          },
          { kind: "trend", metrics: ["deferred"], title: "Deferred revenue balance" },
          { kind: "donut", metric: "revenue", by: "currency", title: "Revenue by currency" },
          { kind: "bars", metric: "invoices", title: "Invoices issued" },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "revenue",
            rows: "entity",
            cols: "revenue_type",
            title: "Revenue by entity and type",
          },
        ],
        table: { entity: "invoice", title: "Invoices", metrics: ["revenue"] },
      },
      {
        key: "vendors",
        label: "Vendor spend",
        description: "Spend concentration and payment terms across vendors.",
        kpis: ["opex", "cogs", "dso", "invoices"],
        widgets: [
          { kind: "ranked", metric: "opex", by: "vendor", title: "Spend by vendor" },
          {
            kind: "treemap",
            metric: "opex",
            outer: "vendor",
            inner: "department",
            title: "Vendor spend by department",
          },
          { kind: "trend", metrics: ["opex"], title: "Vendor spend" },
          { kind: "box", metric: "opex", by: "account", title: "Invoice size by account" },
        ],
        optional: [{ kind: "donut", metric: "opex", by: "account", title: "Spend by account" }],
        table: { entity: "vendor", title: "Vendors", metrics: ["opex", "dso"] },
      },
    ],
  },
  {
    key: "operations",
    label: "Operations",
    icon: "truck",
    accent: "#d4a72c",
    description: "Fulfillment, inventory, suppliers and logistics across the network.",
    team: "Supply Chain",
    headline: ["orders", "on_time", "inventory"],
    scopeAxes: ["warehouse", "category", "carrier"],
    filters: { segment: "shift", region: "region" },
    dimensions: dims({
      warehouse: [
        "Warehouse",
        ["Reno", "Memphis", "Allentown", "Rotterdam", "Leipzig", "Singapore", "Osaka", "Sydney"],
      ],
      category: ["Category", ["Apparel", "Footwear", "Electronics", "Home", "Beauty", "Outdoor"]],
      carrier: ["Carrier", ["UPS", "FedEx", "DHL", "USPS", "Regional"]],
      region: ["Region", REGIONS],
      shift: ["Shift", ["Morning", "Day", "Night"]],
      supplier: [
        "Supplier",
        [
          "Shenzhen Pacific",
          "Monterrey Fab",
          "Hanoi Textiles",
          "Porto Leather",
          "Busan Electronics",
          "Izmir Home",
        ],
      ],
      zone: ["Zone", ["Receiving", "Putaway", "Pick", "Pack", "Ship"]],
      return_reason: [
        "Return reason",
        ["Wrong size", "Damaged", "Not as described", "Late", "Changed mind"],
      ],
      lane: ["Lane", ["West", "Central", "East", "Cross-border", "Air"]],
    }),
    metrics: [
      { key: "orders", label: "Orders", unit: "count", base: 18400, trend: 0.15 },
      { key: "units", label: "Units shipped", unit: "count", base: 52000 },
      { key: "on_time", label: "On-time delivery", unit: "percent", base: 0.94, noise: 0.012 },
      { key: "lead_time", label: "Lead time", unit: "days", base: 3.6, good: "down" },
      {
        key: "inventory",
        label: "Inventory value",
        unit: "currency",
        base: 24_000_000,
        agg: "avg",
        noise: 0.015,
      },
      { key: "stockouts", label: "Stockouts", unit: "count", base: 34, good: "down", noise: 0.25 },
      { key: "fill_rate", label: "Fill rate", unit: "percent", base: 0.965, noise: 0.008 },
      { key: "backorders", label: "Backorders", unit: "count", base: 410, good: "down" },
      {
        key: "cost_per_order",
        label: "Cost per order",
        unit: "currency",
        base: 6.9,
        good: "down",
        agg: "avg",
      },
      { key: "returns", label: "Returns", unit: "count", base: 1500, good: "down" },
      { key: "pick_rate", label: "Picks per hour", unit: "number", base: 118 },
      {
        key: "dock_to_stock",
        label: "Dock to stock",
        unit: "duration",
        base: 19_800_000,
        good: "down",
      },
      {
        key: "utilization",
        label: "Capacity utilization",
        unit: "percent",
        base: 0.81,
        noise: 0.03,
      },
    ],
    entities: {
      shipment: {
        label: "Shipment",
        plural: "Shipments",
        pool: "shipment",
        statuses: ["Delivered", "In transit", "Delayed", "Exception"],
      },
      sku: {
        label: "SKU",
        plural: "SKUs",
        pool: "sku",
        statuses: ["In stock", "Low", "Out of stock", "Discontinued"],
      },
      supplier: {
        label: "Supplier",
        plural: "Suppliers",
        pool: "vendor",
        statuses: ["Approved", "On probation", "Pending"],
      },
    },
    archetypes: [
      {
        key: "fulfillment",
        label: "Fulfillment",
        description: "Orders out the door, on time, and what they cost.",
        kpis: ["orders", "on_time", "lead_time", "cost_per_order"],
        widgets: [
          { kind: "trend", metrics: ["orders", "units"], title: "Orders and units" },
          { kind: "trend", metrics: ["on_time"], title: "On-time delivery" },
          {
            kind: "heatmap",
            metric: "orders",
            rows: "weekday",
            cols: "hour",
            title: "Order volume by hour",
          },
          { kind: "ranked", metric: "orders", by: "carrier", title: "Orders by carrier" },
        ],
        optional: [
          { kind: "histogram", metric: "lead_time", title: "Lead time per order" },
          { kind: "gauge", metric: "on_time", target: 1.02, title: "On-time vs SLA" },
        ],
        table: {
          entity: "shipment",
          title: "Late shipments",
          metrics: ["lead_time", "cost_per_order"],
        },
      },
      {
        key: "inventory",
        label: "Inventory",
        description: "Inventory value, stockouts and fill rate by category.",
        kpis: ["inventory", "fill_rate", "stockouts", "backorders"],
        widgets: [
          {
            kind: "stack",
            metric: "inventory",
            by: "category",
            variant: "stackedArea",
            title: "Inventory value by category",
          },
          { kind: "bars", metric: "stockouts", title: "Stockouts" },
          {
            kind: "treemap",
            metric: "inventory",
            outer: "category",
            inner: "supplier",
            title: "Inventory by category and supplier",
          },
          { kind: "trend", metrics: ["fill_rate"], title: "Fill rate" },
        ],
        optional: [
          {
            kind: "scatter",
            x: "inventory",
            y: "fill_rate",
            by: "category",
            pool: "sku",
            title: "Stock vs fill rate per SKU",
          },
        ],
        table: {
          entity: "sku",
          title: "SKUs at risk",
          metrics: ["inventory", "stockouts", "fill_rate"],
        },
      },
      {
        key: "suppliers",
        label: "Suppliers",
        description: "Lead time, fill rate and defects by supplier.",
        kpis: ["lead_time", "fill_rate", "backorders", "returns"],
        widgets: [
          { kind: "box", metric: "lead_time", by: "supplier", title: "Lead time by supplier" },
          {
            kind: "radar",
            metrics: ["on_time", "fill_rate", "utilization"],
            by: "supplier",
            title: "Supplier scorecard",
          },
          { kind: "ranked", metric: "backorders", by: "supplier", title: "Backorders by supplier" },
          { kind: "trend", metrics: ["lead_time"], title: "Average lead time" },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "lead_time",
            rows: "supplier",
            cols: "month",
            scheme: "oranges",
            title: "Lead time by month",
          },
        ],
        table: { entity: "supplier", title: "Suppliers", metrics: ["lead_time", "fill_rate"] },
      },
      {
        key: "throughput",
        label: "Warehouse throughput",
        description: "Picks, dock-to-stock and utilization through each zone.",
        kpis: ["units", "pick_rate", "dock_to_stock", "utilization"],
        widgets: [
          {
            kind: "heatmap",
            metric: "units",
            rows: "zone",
            cols: "hour",
            title: "Units by zone and hour",
          },
          {
            kind: "stack",
            metric: "units",
            by: "shift",
            variant: "stackedBar",
            title: "Units by shift",
          },
          { kind: "trend", metrics: ["pick_rate"], title: "Picks per hour" },
          { kind: "gauge", metric: "utilization", target: 1.06, title: "Utilization" },
        ],
        optional: [{ kind: "histogram", metric: "dock_to_stock", title: "Dock-to-stock time" }],
        table: { entity: "sku", title: "Fastest movers", metrics: ["units", "pick_rate"] },
      },
      {
        key: "logistics",
        label: "Logistics",
        description: "Carrier performance and shipping cost by lane.",
        kpis: ["on_time", "cost_per_order", "lead_time", "units"],
        widgets: [
          {
            kind: "sankey",
            metric: "units",
            stages: ["category", "carrier", "lane"],
            title: "Units by carrier and lane",
          },
          {
            kind: "radar",
            metrics: ["on_time", "fill_rate", "utilization"],
            by: "carrier",
            title: "Carrier scorecard",
          },
          { kind: "trend", metrics: ["cost_per_order"], title: "Cost per order" },
          { kind: "ranked", metric: "units", by: "lane", title: "Units by lane" },
        ],
        optional: [
          { kind: "box", metric: "lead_time", by: "carrier", title: "Transit time by carrier" },
        ],
        table: { entity: "shipment", title: "Shipments", metrics: ["lead_time", "cost_per_order"] },
      },
      {
        key: "returns",
        label: "Returns",
        description: "Return volume and reasons, and what they cost.",
        kpis: ["returns", "orders", "cost_per_order", "on_time"],
        widgets: [
          { kind: "trend", metrics: ["returns"], title: "Returns" },
          { kind: "donut", metric: "returns", by: "return_reason", title: "Return reasons" },
          {
            kind: "heatmap",
            metric: "returns",
            rows: "category",
            cols: "return_reason",
            title: "Returns by category and reason",
          },
          { kind: "ranked", metric: "returns", by: "category", title: "Returns by category" },
        ],
        optional: [{ kind: "calendar", metric: "returns", title: "Daily returns" }],
        table: { entity: "sku", title: "Most returned SKUs", metrics: ["returns", "units"] },
      },
      {
        key: "capacity",
        label: "Capacity",
        description: "Labor and space capacity against forecast demand.",
        kpis: ["utilization", "orders", "pick_rate", "backorders"],
        widgets: [
          { kind: "combo", bar: "orders", line: "utilization", title: "Orders and utilization" },
          {
            kind: "heatmap",
            metric: "utilization",
            rows: "weekday",
            cols: "hour",
            title: "Utilization by hour",
          },
          { kind: "trend", metrics: ["backorders"], title: "Backorders" },
          { kind: "gauge", metric: "utilization", target: 1.08, title: "Peak readiness" },
        ],
        optional: [
          {
            kind: "stack",
            metric: "orders",
            by: "shift",
            variant: "percentArea",
            title: "Shift mix",
          },
        ],
        table: { entity: "sku", title: "Constrained SKUs", metrics: ["backorders", "units"] },
      },
    ],
  },
  {
    key: "product",
    label: "Product",
    icon: "activity",
    accent: "#8a62d6",
    description: "Engagement, retention, activation and feature adoption.",
    team: "Product Analytics",
    headline: ["dau", "retention", "activation"],
    scopeAxes: ["platform", "plan", "country"],
    filters: { segment: "acquisition", region: "region" },
    dimensions: dims({
      platform: ["Platform", ["Web", "iOS", "Android", "Desktop", "API"]],
      plan: ["Plan", ["Free", "Starter", "Pro", "Business", "Enterprise"]],
      country: ["Country", ["US", "UK", "Germany", "Japan", "Brazil", "India"]],
      region: ["Region", REGIONS],
      acquisition: ["Acquisition", ["Organic", "Paid", "Referral", "Partner", "Sales-led"]],
      feature: [
        "Feature",
        [
          "Saved views",
          "Bulk edit",
          "Workflows",
          "Comments",
          "Exports",
          "Alerts",
          "Templates",
          "Integrations",
        ],
      ],
      variant: ["Variant", ["Control", "Variant A", "Variant B"]],
      screen: ["Screen", ["Home", "Search", "Editor", "Settings", "Billing", "Checkout"]],
      outcome: ["Outcome", ["Converted", "Bounced", "Retried"]],
    }),
    metrics: [
      {
        key: "dau",
        label: "Daily active users",
        unit: "count",
        base: 48000,
        agg: "avg",
        trend: 0.24,
      },
      {
        key: "wau",
        label: "Weekly active users",
        unit: "count",
        base: 131000,
        agg: "avg",
        trend: 0.2,
      },
      { key: "stickiness", label: "DAU / MAU", unit: "percent", base: 0.31 },
      { key: "sessions", label: "Sessions", unit: "count", base: 162000 },
      { key: "session_length", label: "Session length", unit: "duration", base: 412000 },
      { key: "activation", label: "Activation rate", unit: "percent", base: 0.38 },
      { key: "retention", label: "Day-30 retention", unit: "percent", base: 0.27, noise: 0.03 },
      { key: "adoption", label: "Feature adoption", unit: "percent", base: 0.22 },
      { key: "events", label: "Events", unit: "count", base: 8_600_000 },
      {
        key: "crash_free",
        label: "Crash-free sessions",
        unit: "percent",
        base: 0.991,
        noise: 0.002,
      },
      { key: "conversions", label: "Paid conversions", unit: "count", base: 260 },
      { key: "nps", label: "NPS", unit: "number", base: 41, noise: 0.05 },
      { key: "mrr", label: "MRR added", unit: "currency", base: 21500, trend: 0.3 },
    ],
    entities: {
      feature: {
        label: "Feature",
        plural: "Features",
        pool: "feature",
        statuses: ["Live", "Beta", "Rolling out", "Sunset"],
      },
      experiment: {
        label: "Experiment",
        plural: "Experiments",
        pool: "campaign",
        statuses: ["Running", "Won", "Lost", "Inconclusive"],
      },
      account: {
        label: "Workspace",
        plural: "Workspaces",
        pool: "company",
        statuses: ["Active", "Dormant", "Churned", "Expanding"],
      },
    },
    archetypes: [
      {
        key: "engagement",
        label: "Engagement",
        description: "Active users, stickiness and session depth.",
        kpis: ["dau", "wau", "stickiness", "session_length"],
        widgets: [
          { kind: "trend", metrics: ["dau", "wau"], title: "Daily and weekly active users" },
          {
            kind: "heatmap",
            metric: "sessions",
            rows: "weekday",
            cols: "hour",
            scheme: "purples",
            title: "Sessions by hour",
          },
          {
            kind: "stack",
            metric: "sessions",
            by: "platform",
            variant: "stackedArea",
            title: "Sessions by platform",
          },
          { kind: "histogram", metric: "session_length", title: "Session length" },
        ],
        optional: [
          { kind: "calendar", metric: "dau", title: "Daily active users, last year" },
          { kind: "ranked", metric: "sessions", by: "screen", title: "Sessions by entry screen" },
        ],
        table: {
          entity: "account",
          title: "Most active workspaces",
          metrics: ["sessions", "session_length"],
        },
      },
      {
        key: "retention",
        label: "Retention",
        description: "How long new users stay, by signup cohort and plan.",
        kpis: ["retention", "dau", "stickiness", "nps"],
        widgets: [
          {
            kind: "cohort",
            periods: 12,
            grain: "month",
            title: "Monthly retention by signup cohort",
          },
          { kind: "trend", metrics: ["retention"], title: "Day-30 retention" },
          { kind: "ranked", metric: "retention", by: "plan", title: "Retention by plan" },
          { kind: "box", metric: "session_length", by: "plan", title: "Session length by plan" },
        ],
        optional: [
          { kind: "cohort", periods: 10, grain: "week", title: "Weekly retention by signup week" },
        ],
        table: {
          entity: "account",
          title: "Workspaces at risk",
          metrics: ["retention", "sessions"],
        },
      },
      {
        key: "activation",
        label: "Activation",
        description: "From signup to first value: the onboarding funnel.",
        kpis: ["activation", "conversions", "sessions", "retention"],
        widgets: [
          {
            kind: "funnel",
            steps: [
              "Signup",
              "Verified email",
              "Created project",
              "Invited teammate",
              "First report",
              "Activated",
            ],
            top: 9000,
            title: "Onboarding funnel",
          },
          { kind: "trend", metrics: ["activation"], title: "Activation rate" },
          {
            kind: "ranked",
            metric: "activation",
            by: "acquisition",
            title: "Activation by acquisition channel",
          },
          {
            kind: "sankey",
            metric: "sessions",
            stages: ["acquisition", "screen", "outcome"],
            title: "First-session paths",
          },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "activation",
            rows: "platform",
            cols: "plan",
            title: "Activation by platform and plan",
          },
        ],
        table: { entity: "account", title: "New workspaces", metrics: ["activation", "sessions"] },
      },
      {
        key: "features",
        label: "Feature adoption",
        description: "Which features get used, by whom, and how often.",
        kpis: ["adoption", "events", "dau", "nps"],
        widgets: [
          { kind: "ranked", metric: "adoption", by: "feature", title: "Adoption by feature" },
          {
            kind: "heatmap",
            metric: "adoption",
            rows: "feature",
            cols: "plan",
            scheme: "purples",
            title: "Adoption by feature and plan",
          },
          {
            kind: "stack",
            metric: "events",
            by: "feature",
            variant: "stackedBar",
            title: "Events by feature",
          },
          {
            kind: "scatter",
            x: "adoption",
            y: "retention",
            by: "plan",
            pool: "feature",
            title: "Adoption vs retention",
          },
        ],
        optional: [
          {
            kind: "radar",
            metrics: ["adoption", "retention", "stickiness", "activation"],
            by: "platform",
            title: "Platform profile",
          },
        ],
        table: { entity: "feature", title: "Features", metrics: ["adoption", "events"] },
      },
      {
        key: "experiments",
        label: "Experiments",
        description: "Running A/B tests and their effect on conversion.",
        kpis: ["conversions", "activation", "mrr", "sessions"],
        widgets: [
          { kind: "trend", metrics: ["conversions"], title: "Paid conversions" },
          {
            kind: "box",
            metric: "session_length",
            by: "variant",
            title: "Session length by variant",
          },
          { kind: "ranked", metric: "conversions", by: "variant", title: "Conversions by variant" },
          {
            kind: "funnel",
            steps: ["Exposed", "Engaged", "Started trial", "Converted"],
            top: 22000,
            title: "Experiment funnel",
          },
        ],
        optional: [{ kind: "histogram", metric: "mrr", title: "MRR per conversion" }],
        table: {
          entity: "experiment",
          title: "Experiments",
          metrics: ["conversions", "activation"],
        },
      },
      {
        key: "quality",
        label: "Quality",
        description: "Crash-free sessions and performance by platform and release.",
        kpis: ["crash_free", "sessions", "session_length", "nps"],
        widgets: [
          { kind: "trend", metrics: ["crash_free"], title: "Crash-free sessions" },
          { kind: "ranked", metric: "crash_free", by: "platform", title: "Crash-free by platform" },
          {
            kind: "heatmap",
            metric: "crash_free",
            rows: "platform",
            cols: "screen",
            scheme: "greens",
            title: "Crash-free by platform and screen",
          },
          { kind: "gauge", metric: "crash_free", target: 1.004, title: "Crash-free vs target" },
        ],
        optional: [{ kind: "calendar", metric: "sessions", title: "Daily sessions" }],
        table: { entity: "feature", title: "Screens", metrics: ["crash_free", "sessions"] },
      },
      {
        key: "monetization",
        label: "Monetization",
        description: "Upgrades, MRR added and conversion by plan.",
        kpis: ["mrr", "conversions", "activation", "retention"],
        widgets: [
          { kind: "combo", bar: "mrr", line: "activation", title: "MRR added and activation" },
          {
            kind: "sankey",
            metric: "conversions",
            stages: ["acquisition", "plan"],
            title: "Conversions by channel and plan",
          },
          { kind: "donut", metric: "mrr", by: "plan", title: "MRR by plan" },
          { kind: "cumulative", metric: "mrr", target: "mrr", title: "MRR added, cumulative" },
        ],
        optional: [{ kind: "ranked", metric: "mrr", by: "country", title: "MRR by country" }],
        table: { entity: "account", title: "Upgrades", metrics: ["mrr", "conversions"] },
      },
    ],
  },
  {
    key: "infrastructure",
    label: "Infrastructure",
    icon: "server",
    accent: "#2a9fbf",
    description: "Service health, latency, capacity and cloud cost.",
    team: "Platform Engineering",
    headline: ["requests", "availability", "cloud_cost"],
    scopeAxes: ["service", "cloud_region", "env"],
    filters: { segment: "instance_type", region: "cloud_region" },
    dimensions: dims({
      service: [
        "Service",
        ["api-gateway", "auth", "billing", "search", "ingest", "notifications", "reports", "web"],
      ],
      cloud_region: [
        "Cloud region",
        ["us-east", "us-west", "eu-central", "eu-west", "ap-northeast", "ap-southeast"],
      ],
      env: ["Environment", ["production", "staging", "canary"]],
      instance_type: ["Instance family", ["general", "compute", "memory", "storage", "gpu"]],
      endpoint: [
        "Endpoint",
        [
          "GET /v1/items",
          "POST /v1/items",
          "GET /v1/search",
          "POST /v1/events",
          "GET /v1/reports",
          "POST /v1/auth",
        ],
      ],
      status_class: ["Status", ["2xx", "3xx", "4xx", "5xx"]],
      resource: [
        "Resource",
        ["Compute", "Storage", "Network", "Database", "Cache", "Observability"],
      ],
      team: ["Team", ["Core API", "Data", "Identity", "Growth", "Search", "Payments"]],
      severity: ["Severity", ["SEV1", "SEV2", "SEV3", "SEV4"]],
    }),
    metrics: [
      { key: "requests", label: "Requests", unit: "count", base: 186_000_000, trend: 0.3 },
      {
        key: "error_rate",
        label: "Error rate",
        unit: "percent",
        base: 0.0042,
        good: "down",
        noise: 0.18,
      },
      { key: "p50", label: "p50 latency", unit: "duration", base: 42, good: "down" },
      { key: "p95", label: "p95 latency", unit: "duration", base: 230, good: "down", noise: 0.1 },
      { key: "p99", label: "p99 latency", unit: "duration", base: 610, good: "down", noise: 0.14 },
      { key: "cpu", label: "CPU utilization", unit: "percent", base: 0.56 },
      { key: "memory", label: "Memory utilization", unit: "percent", base: 0.68 },
      {
        key: "cloud_cost",
        label: "Cloud cost",
        unit: "currency",
        base: 31000,
        good: "down",
        trend: 0.12,
      },
      { key: "deploys", label: "Deploys", unit: "count", base: 44 },
      { key: "incidents", label: "Incidents", unit: "count", base: 0.9, good: "down", noise: 0.5 },
      { key: "mttr", label: "MTTR", unit: "duration", base: 2_820_000, good: "down", noise: 0.25 },
      { key: "availability", label: "Availability", unit: "percent", base: 0.9993, noise: 0.0004 },
      { key: "egress", label: "Egress", unit: "bytes", base: 9.4e12 },
      { key: "saturation", label: "Queue saturation", unit: "percent", base: 0.34, good: "down" },
    ],
    entities: {
      service: {
        label: "Service",
        plural: "Services",
        pool: "service",
        statuses: ["Healthy", "Degraded", "Outage"],
      },
      deploy: {
        label: "Deploy",
        plural: "Deploys",
        pool: "ticket",
        statuses: ["Live", "Rolled back", "Canary", "Failed"],
      },
      incident: {
        label: "Incident",
        plural: "Incidents",
        pool: "ticket",
        statuses: ["Resolved", "Monitoring", "Open"],
      },
    },
    archetypes: [
      {
        key: "health",
        label: "Service health",
        description: "Golden signals: traffic, errors, latency, saturation.",
        kpis: ["requests", "error_rate", "p95", "availability"],
        widgets: [
          { kind: "trend", metrics: ["requests"], title: "Requests" },
          { kind: "trend", metrics: ["error_rate"], title: "Error rate" },
          { kind: "trend", metrics: ["p50", "p95", "p99"], title: "Latency percentiles" },
          { kind: "gauge", metric: "availability", target: 1.0002, title: "Availability vs SLO" },
        ],
        optional: [
          {
            kind: "stack",
            metric: "requests",
            by: "status_class",
            variant: "percentArea",
            title: "Responses by status",
          },
          {
            kind: "heatmap",
            metric: "requests",
            rows: "weekday",
            cols: "hour",
            title: "Traffic by hour",
          },
        ],
        table: { entity: "service", title: "Services", metrics: ["requests", "error_rate", "p95"] },
      },
      {
        key: "latency",
        label: "Latency",
        description: "Where time goes: latency by endpoint and region.",
        kpis: ["p50", "p95", "p99", "requests"],
        widgets: [
          { kind: "trend", metrics: ["p95", "p99"], title: "Tail latency" },
          {
            kind: "heatmap",
            metric: "p95",
            rows: "endpoint",
            cols: "hour",
            scheme: "oranges",
            title: "p95 by endpoint and hour",
          },
          { kind: "box", metric: "p95", by: "cloud_region", title: "p95 by region" },
          { kind: "histogram", metric: "p50", title: "Request latency distribution" },
        ],
        optional: [
          { kind: "ranked", metric: "p99", by: "endpoint", title: "Slowest endpoints (p99)" },
        ],
        table: { entity: "service", title: "Services by p99", metrics: ["p99", "p95"] },
      },
      {
        key: "errors",
        label: "Errors",
        description: "Error budget burn, error classes and the endpoints producing them.",
        kpis: ["error_rate", "availability", "incidents", "requests"],
        widgets: [
          {
            kind: "stack",
            metric: "requests",
            by: "status_class",
            variant: "stackedBar",
            title: "Responses by status class",
          },
          { kind: "ranked", metric: "error_rate", by: "endpoint", title: "Error rate by endpoint" },
          { kind: "trend", metrics: ["error_rate"], title: "Error rate" },
          { kind: "gauge", metric: "availability", target: 1.0003, title: "Error budget" },
        ],
        optional: [{ kind: "calendar", metric: "incidents", title: "Incidents per day" }],
        table: {
          entity: "service",
          title: "Noisiest services",
          metrics: ["error_rate", "requests"],
        },
      },
      {
        key: "capacity",
        label: "Capacity",
        description: "CPU, memory and queue saturation against headroom targets.",
        kpis: ["cpu", "memory", "saturation", "requests"],
        widgets: [
          { kind: "trend", metrics: ["cpu", "memory"], title: "CPU and memory" },
          {
            kind: "heatmap",
            metric: "cpu",
            rows: "service",
            cols: "hour",
            title: "CPU by service and hour",
          },
          {
            kind: "scatter",
            x: "cpu",
            y: "p95",
            by: "instance_type",
            pool: "service",
            title: "Utilization vs latency per host",
          },
          { kind: "gauge", metric: "cpu", target: 1.25, title: "Headroom" },
        ],
        optional: [{ kind: "trend", metrics: ["saturation"], title: "Queue saturation" }],
        table: { entity: "service", title: "Hottest services", metrics: ["cpu", "memory"] },
      },
      {
        key: "cost",
        label: "Cloud cost",
        description: "Spend by resource, team and region, and its unit economics.",
        kpis: ["cloud_cost", "requests", "egress", "cpu"],
        widgets: [
          {
            kind: "stack",
            metric: "cloud_cost",
            by: "resource",
            variant: "stackedArea",
            title: "Cost by resource",
          },
          {
            kind: "treemap",
            metric: "cloud_cost",
            outer: "team",
            inner: "resource",
            title: "Cost by team and resource",
          },
          { kind: "ranked", metric: "cloud_cost", by: "cloud_region", title: "Cost by region" },
          { kind: "trend", metrics: ["egress"], title: "Egress" },
        ],
        optional: [
          {
            kind: "donut",
            metric: "cloud_cost",
            by: "instance_type",
            title: "Compute by instance family",
          },
        ],
        table: {
          entity: "service",
          title: "Cost per service",
          metrics: ["cloud_cost", "requests"],
        },
      },
      {
        key: "deploys",
        label: "Deployments",
        description: "Deploy frequency, failure rate and lead time for changes.",
        kpis: ["deploys", "mttr", "error_rate", "availability"],
        widgets: [
          { kind: "bars", metric: "deploys", title: "Deploys" },
          {
            kind: "heatmap",
            metric: "deploys",
            rows: "weekday",
            cols: "hour",
            scheme: "greens",
            title: "When we deploy",
          },
          { kind: "ranked", metric: "deploys", by: "team", title: "Deploys by team" },
          { kind: "trend", metrics: ["error_rate"], title: "Error rate around deploys" },
        ],
        optional: [{ kind: "calendar", metric: "deploys", title: "Deploys per day" }],
        table: { entity: "deploy", title: "Recent deploys", metrics: ["deploys", "error_rate"] },
      },
      {
        key: "incidents",
        label: "Incidents",
        description: "Incidents by severity, time to restore and affected services.",
        kpis: ["incidents", "mttr", "availability", "error_rate"],
        widgets: [
          {
            kind: "stack",
            metric: "incidents",
            by: "severity",
            variant: "stackedBar",
            title: "Incidents by severity",
          },
          { kind: "histogram", metric: "mttr", title: "Time to restore" },
          {
            kind: "sankey",
            metric: "incidents",
            stages: ["team", "severity"],
            title: "Incidents by team and severity",
          },
          { kind: "trend", metrics: ["mttr"], title: "MTTR" },
        ],
        optional: [{ kind: "box", metric: "mttr", by: "severity", title: "MTTR by severity" }],
        table: { entity: "incident", title: "Incidents", metrics: ["mttr"] },
      },
    ],
  },
  {
    key: "support",
    label: "Support",
    icon: "headphones",
    accent: "#e0773b",
    description: "Ticket volume, SLAs, satisfaction and agent performance.",
    team: "Customer Support",
    headline: ["tickets", "csat", "first_response"],
    scopeAxes: ["queue", "region", "tier"],
    filters: { segment: "channel", region: "region" },
    dimensions: dims({
      queue: ["Queue", ["Billing", "Technical", "Account", "Onboarding", "Bugs", "Integrations"]],
      region: ["Region", REGIONS],
      tier: ["Tier", ["Standard", "Premium", "Enterprise"]],
      channel: ["Channel", ["Email", "Chat", "Phone", "Community", "In-app"]],
      priority: ["Priority", ["P1", "P2", "P3", "P4"]],
      agent: [
        "Agent",
        [
          "K. Ito",
          "F. Haddad",
          "B. Novak",
          "E. Duarte",
          "G. Brennan",
          "C. Vargas",
          "M. Schmidt",
          "T. Kaur",
        ],
      ],
      topic: [
        "Topic",
        ["Login", "Invoices", "Data import", "Permissions", "API errors", "Performance", "Exports"],
      ],
      resolution: ["Resolution", ["Solved", "Escalated", "Self-served", "Duplicate"]],
    }),
    metrics: [
      { key: "tickets", label: "Tickets", unit: "count", base: 2300, good: "down" },
      {
        key: "backlog",
        label: "Open backlog",
        unit: "count",
        base: 1800,
        agg: "avg",
        good: "down",
        noise: 0.03,
      },
      {
        key: "first_response",
        label: "First response",
        unit: "duration",
        base: 5_400_000,
        good: "down",
      },
      {
        key: "resolution_time",
        label: "Resolution time",
        unit: "duration",
        base: 64_800_000,
        good: "down",
      },
      { key: "csat", label: "CSAT", unit: "percent", base: 0.91, noise: 0.012 },
      { key: "sla_met", label: "SLA met", unit: "percent", base: 0.93, noise: 0.015 },
      { key: "reopen", label: "Reopen rate", unit: "percent", base: 0.06, good: "down" },
      { key: "deflection", label: "Self-service deflection", unit: "percent", base: 0.34 },
      { key: "handle_time", label: "Handle time", unit: "duration", base: 690_000, good: "down" },
      { key: "escalations", label: "Escalations", unit: "count", base: 85, good: "down" },
      { key: "contacts", label: "Contacts per customer", unit: "number", base: 1.4, good: "down" },
    ],
    entities: {
      ticket: {
        label: "Ticket",
        plural: "Tickets",
        pool: "ticket",
        statuses: ["Open", "Pending", "Resolved", "Escalated", "Breached"],
      },
      agent: {
        label: "Agent",
        plural: "Agents",
        pool: "person",
        statuses: ["Online", "Away", "Offline"],
      },
      article: {
        label: "Article",
        plural: "Articles",
        pool: "feature",
        statuses: ["Published", "Draft", "Outdated"],
      },
    },
    archetypes: [
      {
        key: "overview",
        label: "Support overview",
        description: "Volume, backlog, response times and satisfaction.",
        kpis: ["tickets", "backlog", "first_response", "csat"],
        widgets: [
          { kind: "trend", metrics: ["tickets"], title: "Tickets created" },
          {
            kind: "stack",
            metric: "tickets",
            by: "channel",
            variant: "stackedArea",
            title: "Tickets by channel",
          },
          {
            kind: "heatmap",
            metric: "tickets",
            rows: "weekday",
            cols: "hour",
            scheme: "oranges",
            title: "When tickets arrive",
          },
          { kind: "ranked", metric: "tickets", by: "topic", title: "Top topics" },
        ],
        optional: [
          { kind: "calendar", metric: "tickets", title: "Tickets per day" },
          { kind: "donut", metric: "tickets", by: "priority", title: "Tickets by priority" },
        ],
        table: {
          entity: "ticket",
          title: "Oldest open tickets",
          metrics: ["first_response", "resolution_time"],
        },
      },
      {
        key: "sla",
        label: "SLA",
        description: "Response and resolution SLAs by priority and tier.",
        kpis: ["sla_met", "first_response", "resolution_time", "escalations"],
        widgets: [
          { kind: "trend", metrics: ["sla_met"], title: "SLA attainment" },
          {
            kind: "box",
            metric: "first_response",
            by: "priority",
            title: "First response by priority",
          },
          {
            kind: "heatmap",
            metric: "sla_met",
            rows: "priority",
            cols: "channel",
            scheme: "greens",
            title: "SLA met by priority and channel",
          },
          { kind: "gauge", metric: "sla_met", target: 1.03, title: "SLA vs target" },
        ],
        optional: [{ kind: "histogram", metric: "resolution_time", title: "Resolution time" }],
        table: {
          entity: "ticket",
          title: "Breached tickets",
          metrics: ["first_response", "resolution_time"],
        },
      },
      {
        key: "csat",
        label: "Satisfaction",
        description: "CSAT and reopen rate by topic, channel and agent.",
        kpis: ["csat", "reopen", "contacts", "resolution_time"],
        widgets: [
          { kind: "trend", metrics: ["csat"], title: "CSAT" },
          { kind: "ranked", metric: "csat", by: "topic", title: "CSAT by topic" },
          {
            kind: "scatter",
            x: "resolution_time",
            y: "csat",
            by: "channel",
            pool: "ticket",
            title: "Resolution time vs CSAT",
          },
          {
            kind: "radar",
            metrics: ["csat", "sla_met", "deflection"],
            by: "channel",
            title: "Channel scorecard",
          },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "csat",
            rows: "topic",
            cols: "channel",
            scheme: "greens",
            title: "CSAT by topic and channel",
          },
        ],
        table: { entity: "agent", title: "Agents by CSAT", metrics: ["csat", "reopen"] },
      },
      {
        key: "backlog",
        label: "Backlog",
        description: "Open tickets by age and queue, inflow against outflow.",
        kpis: ["backlog", "tickets", "resolution_time", "escalations"],
        widgets: [
          { kind: "trend", metrics: ["backlog"], title: "Open backlog" },
          { kind: "combo", bar: "tickets", line: "backlog", title: "Inflow and backlog" },
          {
            kind: "treemap",
            metric: "backlog",
            outer: "priority",
            inner: "topic",
            title: "Backlog by priority and topic",
          },
          { kind: "ranked", metric: "backlog", by: "topic", title: "Backlog by topic" },
        ],
        optional: [
          {
            kind: "stack",
            metric: "backlog",
            by: "priority",
            variant: "stackedBar",
            title: "Backlog by priority",
          },
        ],
        table: { entity: "ticket", title: "Aging tickets", metrics: ["resolution_time"] },
      },
      {
        key: "agents",
        label: "Agents",
        description: "Throughput, handle time and quality per agent.",
        kpis: ["handle_time", "tickets", "csat", "reopen"],
        widgets: [
          { kind: "ranked", metric: "tickets", by: "agent", title: "Tickets solved by agent" },
          {
            kind: "heatmap",
            metric: "tickets",
            rows: "agent",
            cols: "weekday",
            title: "Tickets by agent and weekday",
          },
          { kind: "box", metric: "handle_time", by: "channel", title: "Handle time by channel" },
          {
            kind: "scatter",
            x: "handle_time",
            y: "csat",
            by: "tier",
            pool: "person",
            title: "Handle time vs CSAT per agent",
          },
        ],
        optional: [{ kind: "trend", metrics: ["handle_time"], title: "Average handle time" }],
        table: { entity: "agent", title: "Agents", metrics: ["tickets", "handle_time", "csat"] },
      },
      {
        key: "deflection",
        label: "Self-service",
        description: "Help center deflection and the articles that resolve questions.",
        kpis: ["deflection", "tickets", "contacts", "csat"],
        widgets: [
          { kind: "trend", metrics: ["deflection"], title: "Deflection rate" },
          {
            kind: "funnel",
            steps: ["Help center visit", "Searched", "Read article", "Resolved", "No ticket"],
            top: 41000,
            title: "Self-service funnel",
          },
          { kind: "ranked", metric: "deflection", by: "topic", title: "Deflection by topic" },
          {
            kind: "sankey",
            metric: "tickets",
            stages: ["channel", "resolution"],
            title: "Contact paths",
          },
        ],
        optional: [{ kind: "donut", metric: "tickets", by: "resolution", title: "Resolutions" }],
        table: { entity: "article", title: "Top articles", metrics: ["deflection"] },
      },
      {
        key: "escalations",
        label: "Escalations",
        description: "What gets escalated to engineering, and how fast it comes back.",
        kpis: ["escalations", "resolution_time", "reopen", "sla_met"],
        widgets: [
          { kind: "bars", metric: "escalations", title: "Escalations" },
          { kind: "donut", metric: "escalations", by: "topic", title: "Escalations by topic" },
          { kind: "histogram", metric: "resolution_time", title: "Time to resolve escalations" },
          {
            kind: "heatmap",
            metric: "escalations",
            rows: "topic",
            cols: "priority",
            scheme: "oranges",
            title: "Escalations by topic and priority",
          },
        ],
        optional: [{ kind: "trend", metrics: ["reopen"], title: "Reopen rate" }],
        table: { entity: "ticket", title: "Escalated tickets", metrics: ["resolution_time"] },
      },
    ],
  },
  {
    key: "people",
    label: "People",
    icon: "users",
    accent: "#5aa346",
    description: "Headcount, hiring, attrition and engagement across the company.",
    team: "People Analytics",
    headline: ["headcount", "hires", "attrition"],
    scopeAxes: ["department", "location", "level"],
    filters: { segment: "employment", region: "region" },
    dimensions: dims({
      department: [
        "Department",
        [
          "Engineering",
          "Sales",
          "Marketing",
          "G&A",
          "Customer Success",
          "Product",
          "Operations",
          "Design",
        ],
      ],
      location: ["Location", ["San Francisco", "New York", "London", "Berlin", "Tokyo", "Remote"]],
      level: ["Level", ["IC1-2", "IC3", "IC4", "IC5+", "Manager", "Director+"]],
      region: ["Region", REGIONS],
      employment: ["Employment", ["Full-time", "Part-time", "Contractor"]],
      tenure: ["Tenure", ["<1y", "1-2y", "2-4y", "4y+"]],
      source: ["Hiring source", ["Referral", "Inbound", "Sourced", "Agency", "University"]],
      stage: ["Stage", ["Applied", "Screen", "Onsite", "Offer", "Hired"]],
      exit_reason: [
        "Exit reason",
        ["Compensation", "Career growth", "Manager", "Relocation", "Performance", "Other"],
      ],
    }),
    metrics: [
      {
        key: "headcount",
        label: "Headcount",
        unit: "count",
        base: 2840,
        agg: "avg",
        trend: 0.12,
        noise: 0.002,
        season: 0,
      },
      { key: "hires", label: "Hires", unit: "count", base: 4.1, noise: 0.35 },
      {
        key: "attrition",
        label: "Attrition (annualized)",
        unit: "percent",
        base: 0.11,
        good: "down",
        noise: 0.1,
      },
      { key: "open_roles", label: "Open roles", unit: "count", base: 186, agg: "avg", noise: 0.03 },
      { key: "time_to_hire", label: "Time to hire", unit: "days", base: 38, good: "down" },
      { key: "offer_accept", label: "Offer acceptance", unit: "percent", base: 0.84, noise: 0.04 },
      { key: "engagement", label: "Engagement score", unit: "percent", base: 0.76, noise: 0.01 },
      {
        key: "comp_cost",
        label: "Compensation cost",
        unit: "currency",
        base: 1_160_000,
        good: "down",
        noise: 0.01,
      },
      { key: "training", label: "Training hours", unit: "count", base: 640 },
      { key: "mobility", label: "Internal moves", unit: "count", base: 1.6, noise: 0.4 },
      { key: "span", label: "Span of control", unit: "number", base: 6.4, noise: 0.02 },
      { key: "applicants", label: "Applicants", unit: "count", base: 690 },
    ],
    entities: {
      req: {
        label: "Requisition",
        plural: "Requisitions",
        pool: "role",
        statuses: ["Open", "Interviewing", "Offer", "Filled", "On hold"],
      },
      team: {
        label: "Team",
        plural: "Teams",
        pool: "person",
        statuses: ["Growing", "Stable", "At risk"],
      },
    },
    archetypes: [
      {
        key: "headcount",
        label: "Headcount",
        description: "Headcount and its composition by level, location and tenure.",
        kpis: ["headcount", "hires", "attrition", "span"],
        widgets: [
          { kind: "trend", metrics: ["headcount"], title: "Headcount" },
          {
            kind: "treemap",
            metric: "headcount",
            outer: "level",
            inner: "location",
            title: "Headcount by level and location",
          },
          { kind: "donut", metric: "headcount", by: "tenure", title: "Tenure mix" },
          { kind: "ranked", metric: "headcount", by: "location", title: "Headcount by location" },
        ],
        optional: [
          {
            kind: "stack",
            metric: "headcount",
            by: "employment",
            variant: "percentArea",
            title: "Employment type mix",
          },
        ],
        table: { entity: "team", title: "Teams", metrics: ["headcount", "attrition"] },
      },
      {
        key: "hiring",
        label: "Hiring",
        description: "Recruiting funnel, time to hire and offer acceptance.",
        kpis: ["hires", "open_roles", "time_to_hire", "offer_accept"],
        widgets: [
          {
            kind: "funnel",
            steps: ["Applied", "Screened", "Onsite", "Offer", "Accepted"],
            top: 6200,
            title: "Recruiting funnel",
          },
          {
            kind: "sankey",
            metric: "applicants",
            stages: ["source", "stage"],
            title: "Candidates by source and stage",
          },
          { kind: "trend", metrics: ["time_to_hire"], title: "Time to hire" },
          { kind: "ranked", metric: "hires", by: "source", title: "Hires by source" },
        ],
        optional: [
          { kind: "box", metric: "time_to_hire", by: "level", title: "Time to hire by level" },
        ],
        table: {
          entity: "req",
          title: "Open requisitions",
          metrics: ["time_to_hire", "applicants"],
        },
      },
      {
        key: "attrition",
        label: "Attrition",
        description: "Who leaves, when and why.",
        kpis: ["attrition", "headcount", "engagement", "mobility"],
        widgets: [
          { kind: "trend", metrics: ["attrition"], title: "Attrition (annualized)" },
          { kind: "donut", metric: "attrition", by: "exit_reason", title: "Exit reasons" },
          {
            kind: "heatmap",
            metric: "attrition",
            rows: "level",
            cols: "tenure",
            scheme: "oranges",
            title: "Attrition by level and tenure",
          },
          { kind: "cohort", periods: 8, grain: "month", title: "Retention of hiring cohorts" },
        ],
        optional: [
          { kind: "ranked", metric: "attrition", by: "location", title: "Attrition by location" },
        ],
        table: { entity: "team", title: "Teams at risk", metrics: ["attrition", "engagement"] },
      },
      {
        key: "engagement",
        label: "Engagement",
        description: "Survey engagement and its drivers.",
        kpis: ["engagement", "attrition", "training", "mobility"],
        widgets: [
          { kind: "trend", metrics: ["engagement"], title: "Engagement score" },
          {
            kind: "radar",
            metrics: ["engagement", "offer_accept", "attrition"],
            by: "level",
            title: "Engagement drivers by level",
          },
          { kind: "ranked", metric: "engagement", by: "location", title: "Engagement by location" },
          {
            kind: "scatter",
            x: "engagement",
            y: "attrition",
            by: "level",
            pool: "person",
            title: "Engagement vs attrition per team",
          },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "engagement",
            rows: "level",
            cols: "location",
            scheme: "greens",
            title: "Engagement by level and location",
          },
        ],
        table: { entity: "team", title: "Teams", metrics: ["engagement", "training"] },
      },
      {
        key: "compensation",
        label: "Compensation",
        description: "Compensation cost and its distribution by level.",
        kpis: ["comp_cost", "headcount", "hires", "span"],
        widgets: [
          { kind: "trend", metrics: ["comp_cost"], title: "Compensation cost" },
          { kind: "box", metric: "comp_cost", by: "level", title: "Compensation by level" },
          {
            kind: "treemap",
            metric: "comp_cost",
            outer: "location",
            inner: "level",
            title: "Cost by location and level",
          },
          { kind: "histogram", metric: "comp_cost", title: "Compensation distribution" },
        ],
        optional: [{ kind: "ranked", metric: "comp_cost", by: "level", title: "Cost by level" }],
        table: { entity: "team", title: "Teams by cost", metrics: ["comp_cost", "headcount"] },
      },
      {
        key: "learning",
        label: "Learning",
        description: "Training hours, internal mobility and promotions.",
        kpis: ["training", "mobility", "engagement", "headcount"],
        widgets: [
          { kind: "bars", metric: "training", title: "Training hours" },
          {
            kind: "sankey",
            metric: "mobility",
            stages: ["level", "tenure"],
            title: "Internal moves by level and tenure",
          },
          { kind: "ranked", metric: "training", by: "level", title: "Training by level" },
          { kind: "calendar", metric: "training", title: "Training hours per day" },
        ],
        optional: [{ kind: "trend", metrics: ["mobility"], title: "Internal moves" }],
        table: { entity: "team", title: "Teams", metrics: ["training", "mobility"] },
      },
      {
        key: "org-health",
        label: "Org health",
        description: "Spans and layers, manager load and open roles.",
        kpis: ["span", "open_roles", "headcount", "engagement"],
        widgets: [
          { kind: "trend", metrics: ["open_roles"], title: "Open roles" },
          {
            kind: "heatmap",
            metric: "span",
            rows: "level",
            cols: "location",
            title: "Span of control",
          },
          { kind: "box", metric: "span", by: "location", title: "Team size by location" },
          { kind: "gauge", metric: "span", target: 1.1, title: "Span vs target" },
        ],
        optional: [
          { kind: "donut", metric: "open_roles", by: "level", title: "Open roles by level" },
        ],
        table: { entity: "req", title: "Roles to fill", metrics: ["time_to_hire"] },
      },
    ],
  },
  {
    key: "commerce",
    label: "Commerce",
    icon: "cart",
    accent: "#b85c38",
    description: "Storefront sales, merchandising, promotions and customers.",
    team: "E-commerce",
    headline: ["gmv", "orders", "aov"],
    scopeAxes: ["category", "channel", "country"],
    filters: { segment: "customer_type", region: "region" },
    dimensions: dims({
      category: ["Category", ["Apparel", "Footwear", "Accessories", "Home", "Beauty", "Outdoor"]],
      channel: ["Channel", ["Web", "App", "Marketplace", "Retail"]],
      country: ["Country", ["US", "UK", "Germany", "France", "Japan", "Australia"]],
      region: ["Region", REGIONS],
      customer_type: ["Customer type", ["New", "Returning", "VIP"]],
      device: ["Device", ["Desktop", "Mobile", "Tablet"]],
      payment: ["Payment", ["Card", "Wallet", "BNPL", "Gift card", "Bank transfer"]],
      promotion: ["Promotion", ["None", "Sitewide", "Bundle", "Free shipping", "Loyalty"]],
      step: ["Checkout step", ["Cart", "Shipping", "Payment", "Review", "Complete"]],
    }),
    metrics: [
      { key: "gmv", label: "GMV", unit: "currency", base: 520000, trend: 0.17, season: 0.22 },
      { key: "orders", label: "Orders", unit: "count", base: 6100, season: 0.22 },
      { key: "aov", label: "Avg order value", unit: "currency", base: 86, agg: "avg" },
      { key: "conversion", label: "Conversion rate", unit: "percent", base: 0.029 },
      {
        key: "abandonment",
        label: "Cart abandonment",
        unit: "percent",
        base: 0.68,
        good: "down",
        noise: 0.02,
      },
      { key: "units", label: "Units sold", unit: "count", base: 14800, season: 0.22 },
      { key: "refunds", label: "Refunds", unit: "currency", base: 21000, good: "down" },
      { key: "margin", label: "Gross margin", unit: "percent", base: 0.52, noise: 0.02 },
      { key: "visitors", label: "Visitors", unit: "count", base: 210000, season: 0.18 },
      { key: "repeat", label: "Repeat purchase rate", unit: "percent", base: 0.31 },
      { key: "redemptions", label: "Promo redemptions", unit: "count", base: 1900, noise: 0.15 },
      { key: "ltv", label: "Customer LTV", unit: "currency", base: 412, noise: 0.03, agg: "avg" },
    ],
    entities: {
      product: {
        label: "Product",
        plural: "Products",
        pool: "product",
        statuses: ["Active", "Low stock", "Out of stock", "Draft"],
      },
      sku: {
        label: "SKU",
        plural: "SKUs",
        pool: "sku",
        statuses: ["Active", "Low stock", "Discontinued"],
      },
      customer: {
        label: "Customer",
        plural: "Customers",
        pool: "person",
        statuses: ["VIP", "Active", "Lapsed"],
      },
    },
    archetypes: [
      {
        key: "storefront",
        label: "Storefront",
        description: "GMV, orders, conversion and average order value.",
        kpis: ["gmv", "orders", "conversion", "aov"],
        widgets: [
          { kind: "trend", metrics: ["gmv"], title: "GMV" },
          { kind: "combo", bar: "orders", line: "conversion", title: "Orders and conversion" },
          {
            kind: "heatmap",
            metric: "orders",
            rows: "weekday",
            cols: "hour",
            title: "Orders by hour",
          },
          { kind: "donut", metric: "gmv", by: "device", title: "GMV by device" },
        ],
        optional: [
          { kind: "calendar", metric: "gmv", title: "Daily GMV" },
          { kind: "ranked", metric: "gmv", by: "category", title: "GMV by category" },
        ],
        table: { entity: "product", title: "Best sellers", metrics: ["gmv", "units", "margin"] },
      },
      {
        key: "merchandising",
        label: "Merchandising",
        description: "Category and product performance, sell-through and margin.",
        kpis: ["units", "margin", "gmv", "refunds"],
        widgets: [
          {
            kind: "treemap",
            metric: "gmv",
            outer: "category",
            inner: "promotion",
            title: "GMV by category and promotion",
          },
          {
            kind: "stack",
            metric: "units",
            by: "category",
            variant: "stackedBar",
            title: "Units by category",
          },
          {
            kind: "scatter",
            x: "units",
            y: "margin",
            by: "category",
            pool: "product",
            title: "Volume vs margin per product",
          },
          { kind: "ranked", metric: "margin", by: "category", title: "Margin by category" },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "units",
            rows: "category",
            cols: "month",
            title: "Units by category and month",
          },
        ],
        table: { entity: "product", title: "Products", metrics: ["units", "margin", "gmv"] },
      },
      {
        key: "promotions",
        label: "Promotions",
        description: "Redemptions, incremental GMV and margin cost of promotions.",
        kpis: ["redemptions", "gmv", "margin", "aov"],
        widgets: [
          {
            kind: "stack",
            metric: "gmv",
            by: "promotion",
            variant: "stackedArea",
            title: "GMV by promotion",
          },
          { kind: "ranked", metric: "redemptions", by: "promotion", title: "Redemptions" },
          { kind: "box", metric: "aov", by: "promotion", title: "Order value by promotion" },
          { kind: "trend", metrics: ["margin"], title: "Gross margin" },
        ],
        optional: [
          {
            kind: "radar",
            metrics: ["conversion", "margin", "repeat"],
            by: "promotion",
            title: "Promotion scorecard",
          },
        ],
        table: { entity: "sku", title: "Promoted SKUs", metrics: ["redemptions", "margin"] },
      },
      {
        key: "customers",
        label: "Customers",
        description: "New and returning customers, repeat rate and lifetime value.",
        kpis: ["repeat", "ltv", "orders", "aov"],
        widgets: [
          {
            kind: "cohort",
            periods: 12,
            grain: "month",
            title: "Repeat purchase by first-order cohort",
          },
          {
            kind: "stack",
            metric: "orders",
            by: "customer_type",
            variant: "stackedBar",
            title: "Orders by customer type",
          },
          { kind: "histogram", metric: "ltv", title: "LTV distribution" },
          { kind: "trend", metrics: ["repeat"], title: "Repeat purchase rate" },
        ],
        optional: [
          { kind: "ranked", metric: "ltv", by: "channel", title: "LTV by acquisition channel" },
        ],
        table: { entity: "customer", title: "Top customers", metrics: ["ltv", "orders"] },
      },
      {
        key: "checkout",
        label: "Checkout",
        description: "Where shoppers drop out of checkout, by device and payment.",
        kpis: ["conversion", "abandonment", "orders", "aov"],
        widgets: [
          {
            kind: "funnel",
            steps: ["Product view", "Add to cart", "Checkout", "Payment", "Order"],
            top: 210000,
            title: "Purchase funnel",
          },
          { kind: "trend", metrics: ["abandonment"], title: "Cart abandonment" },
          { kind: "donut", metric: "orders", by: "payment", title: "Orders by payment method" },
          {
            kind: "sankey",
            metric: "visitors",
            stages: ["device", "step"],
            title: "Checkout paths by device",
          },
        ],
        optional: [
          {
            kind: "heatmap",
            metric: "abandonment",
            rows: "device",
            cols: "payment",
            scheme: "oranges",
            title: "Abandonment by device and payment",
          },
        ],
        table: { entity: "sku", title: "Most abandoned SKUs", metrics: ["abandonment", "units"] },
      },
      {
        key: "marketplace",
        label: "Marketplace",
        description: "Third-party marketplace sales and fees.",
        kpis: ["gmv", "orders", "refunds", "margin"],
        widgets: [
          { kind: "trend", metrics: ["gmv", "refunds"], title: "Marketplace GMV and refunds" },
          { kind: "ranked", metric: "gmv", by: "country", title: "GMV by country" },
          {
            kind: "treemap",
            metric: "gmv",
            outer: "country",
            inner: "category",
            title: "GMV by country and category",
          },
          { kind: "bars", metric: "orders", title: "Orders" },
        ],
        optional: [{ kind: "box", metric: "aov", by: "country", title: "Order value by country" }],
        table: { entity: "product", title: "Marketplace listings", metrics: ["gmv", "refunds"] },
      },
      {
        key: "refunds",
        label: "Refunds",
        description: "Refund value and rate by category and channel.",
        kpis: ["refunds", "gmv", "margin", "repeat"],
        widgets: [
          { kind: "trend", metrics: ["refunds"], title: "Refunds" },
          { kind: "ranked", metric: "refunds", by: "category", title: "Refunds by category" },
          {
            kind: "heatmap",
            metric: "refunds",
            rows: "category",
            cols: "channel",
            scheme: "oranges",
            title: "Refunds by category and channel",
          },
          { kind: "donut", metric: "refunds", by: "payment", title: "Refunds by payment method" },
        ],
        optional: [{ kind: "calendar", metric: "refunds", title: "Daily refunds" }],
        table: { entity: "product", title: "Most refunded", metrics: ["refunds", "units"] },
      },
    ],
  },
];

export const REFRESH = ["Updated hourly", "Updated every 15 min", "Updated daily at 06:00", "Live"];
